### ISSUE TITLE
Errors when attempting to submit invalid decklist

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#280]
Example curl:
```
curl 'http://localhost:5173/api/dev/APIs/CreateGame.php' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:5173/' -H 'content-type: application/json' -H 'Origin: http://localhost:5173' -H 'Connection: keep-alive' -H 'Cookie: PHPSESSID=uo499cc9mtms3lojbmaaan28te; lastAuthKey=c58a132789029c88d8a32a34748514b2f49943e0488a0beface2a72655f4d85a' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"deck":"","fabdb":"https://fabrary.net/decks/01GBJVTDXPQSVEE6ZC3ZWYEQQ6t","deckTestMode":true,"format":"blitz","visibility":"private","decksToTry":"","favoriteDeck":false,"favoriteDecks":"","gameDescription":""}'
```
response:
```
<br />
<b>Warning</b>:  Undefined property: stdClass::$name in <b>/var/www/html/game/APIs/JoinGame.php</b> on line <b>128</b><br />
<br />
<b>Warning</b>:  Undefined property: stdClass::$cards in <b>/var/www/html/game/APIs/JoinGame.php</b> on line <b>134</b><br />
{"error":"Decklist link invalid."}<br />
<b>Warning</b>:  fopen(./BugReports/LoadDeckFailure.txt): Failed to open stream: No such file or directory in <b>/var/www/html/game/APIs/JoinGame.php</b> on line <b>711</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/game/APIs/JoinGame.php:715
Stack trace:
#0 /var/www/html/game/APIs/JoinGame.php(715): fwrite(false, 'Deck load failu...')
#1 /var/www/html/game/APIs/JoinGame.php(298): LogDeckLoadFailure('Decklist link i...')
#2 /var/www/html/game/APIs/CreateGame.php(114): include('/var/www/html/g...')
#3 {main}
  thrown in <b>/var/www/html/game/APIs/JoinGame.php</b> on line <b>715</b><br />
```

**Comment by OotTheMonk** [comment]
Added error handling and proper return value, now this shows up really nice :)
Revision cf0a5e38
![image](https://user-images.githubusercontent.com/77394768/218611454-d899a2e6-4e8c-4112-ac1d-c5e5f553318e.png)
